r"""The terminal's welcome art, written to src/data/terminal-art.ts.

    python scripts/build-terminal-art.py

- NAME_BANNER: the owner's "KEVAN" banner, verbatim from scripts/art/kevan-banner.txt.
- SQUIRTLE: Squirtle from Pokémon Blue's title screen as block text art, one Game Boy pixel per two characters
  (so each pixel is roughly square): white is a full block, light grey a medium shade, dark grey a light shade,
  black is left blank, like the outline gaps in classic text art. scripts/art/squirtle-blue-title.png is the
  title-screen Squirtle recovered at Game Boy resolution (46 x 37, four shades) from a screenshot the owner
  supplied: the screen's 7.5x pixel grid was sampled at each pixel's centre and snapped to the four shades.
"""
from collections import deque
from pathlib import Path
from PIL import Image
import numpy as np

ROOT = Path(__file__).resolve().parent.parent
ART = ROOT / "scripts/art"
SHADES = {255: "█", 170: "▒", 85: "░", 0: " "}


def block_art(path):
    a = np.asarray(Image.open(path).convert("L")).astype(int)
    a = np.array([[min(SHADES, key=lambda s: abs(s - v)) for v in row] for row in a])
    h, w = a.shape
    # White that touches the edge is background, not Squirtle: flood it out
    outside = np.zeros_like(a, bool)
    queue = deque([(y, x) for y in range(h) for x in (0, w - 1)] + [(y, x) for x in range(w) for y in (0, h - 1)])
    while queue:
        y, x = queue.popleft()
        if 0 <= y < h and 0 <= x < w and not outside[y, x] and a[y, x] == 255:
            outside[y, x] = True
            queue.extend(((y + 1, x), (y - 1, x), (y, x + 1), (y, x - 1)))
    rows = ["".join((" " if outside[y, x] else SHADES[a[y, x]]) * 2 for x in range(w)).rstrip() for y in range(h)]
    while rows and not rows[0].strip(): rows.pop(0)
    while rows and not rows[-1].strip(): rows.pop()
    indent = min(len(r) - len(r.lstrip()) for r in rows if r.strip())
    return [r[indent:] for r in rows]


def literal(rows):
    return "`" + "\n".join(rows).replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${") + "`"


if __name__ == "__main__":
    banner = [r.rstrip() for r in (ART / "kevan-banner.txt").read_text(encoding="utf-8").splitlines()]
    squirtle = block_art(ART / "squirtle-blue-title.png")
    out = ROOT / "src/data/terminal-art.ts"
    out.write_text("// Generated by scripts/build-terminal-art.py. Do not edit by hand.\n"
                   f"export const NAME_BANNER = {literal(banner)};\n\n"
                   f"export const SQUIRTLE = {literal(squirtle)};\n", encoding="utf-8")
    print(f"{out.relative_to(ROOT)}: banner {len(banner)} rows x {max(map(len, banner))}, squirtle {len(squirtle)} x {max(map(len, squirtle))}")
